### ISSUE TITLE
How to get the initial offset value

### ISSUE THREAD

**Issue by Sumukha1496** [SOHU-Co/kafka-node#1102]
##

* I am working on a project to search records based on offset.(I have only one partition) My older messages got deleted due to ttl and my initial offset is no longer 0. I want to know the updated initial offset. How to get the initial offset value?

**Comment by ahmedlafta** [comment]
```javascript
this.offset = new kafka.Offset(new kafka.KafkaClient({opts}));
this.offset.on('ready', () => {
    this.offset.fetchEarliestOffsets(topicName, (error, offsets) => {
        const keys = Object.keys(offsets[this.topic]);
        for (let i = 0; i < keys.length; i++) { // iterate over the partitions
            let partition = keys[i];
            let partitionOffset = offsets[topicName][keys[i]];
            this.consumerGroup.setOffset(this.topic, partition, partitionOffset); // if you have a consumer group already defined, you can set each individual partition at the offset you found
          }
    });
```

To be safe, I also pause my consumer group before resetting the offset. See https://github.com/SOHU-Co/kafka-node#fetchearliestoffsetstopics-cb and https://github.com/SOHU-Co/kafka-node#setoffsettopic-partition-offset-1 for more info. Also, rather than creating a new kafkaClient, you can reuse the consumer group's client by `this.consumerGroup.client` although it's probably not best practice.

**Comment by Sumukha1496** [comment]
It works. Thank you.
