### ISSUE TITLE
Error handling on connection

### ISSUE THREAD

**Issue by AndrewKeig** [SOHU-Co/kafka-node#117]
Hi

I noticed a recent issue #103, which I think attempted to resolve this issue.  When kafka is not available, or the host provided to `kafka.client` is wrong, how can I detect this?  The error handlers in this example are never hit..   The example below creates a topic; it will not time out, and no error is reported; it simply repeats the process of trying to create a topic.  If kafka fails for whatever reason we cannot recover on the application side, the application will never know.

```
var kafka = require('kafka-node'),
    Producer = kafka.Producer,
    client = new kafka.Client('wrong'),
    producer = new Producer(client);

    client.on('error', function (err) {
        console.log(err);
    });

    producer.on('error', function (err) {
        console.log(err);
    });

    producer.createTopics(['some-topic'], true, function (err, data) {
      console.log(data);
    });

```

**Comment by alph486** [comment]
bump. I'm able to connect to a local Kafka instance via shell but the library will not. I'd love to debug but I don't get any notifications if ZK connect fails.

**Comment by mwaarna** [comment]
bump!  
This is a critical issue. 

the on error event should be triggered or a new event added when connection fails.

**Comment by florentvaldelievre** [comment]
+1

**Comment by reemdiab** [comment]
+1

**Comment by naderchehab** [comment]
+1

**Comment by estliberitas** [comment]
Fix was proposed long long time ago and no changes since then: alexguan/node-zookeeper-client#16

**Comment by samypr100** [comment]
+1

**Comment by Petrox** [comment]
+1

**Comment by codeofsumit** [comment]
+1

**Comment by Infra-dev** [comment]
+1

**Comment by linxuanwei** [comment]
+1

**Comment by Insferatu** [comment]
+1

**Comment by danielnuriyev** [comment]
+1

**Comment by vivekpathak** [comment]
One way to handle this situation is to open a timeout with `setTimeout` before you send.  The timeout would close the connection (and wait for callback) and then reconnect before calling send with the same parameters.  This way you dont hang and come out even if kafka/zookeeper are down. 

On the non error side, once the (original) send completes, the timeout  should be cleared with `clearTimeout` because there is no need to resend.

It seems to work well when kafka/zk are up and recovers nicely from a restart.

**Comment by gnitsenko93** [comment]
@vivekpathak despite it is quite smart way this is still a workaround!

+1 for a native support

**Comment by respinha-ribeiro** [comment]
+1

**Comment by ayZagen** [comment]
+1

**Comment by benitojcv** [comment]
+1

**Comment by jean507** [comment]
+1

**Comment by AndrewKeig** [comment]
lol, 3 years and counting...

**Comment by jogaklaa** [comment]
+1

**Comment by mihaimm** [comment]
+1

**Comment by clodio** [comment]
+1

**Comment by xbabinec** [comment]
+1

**Comment by amirabiri** [comment]
@AndrewKeig - It's not related to Kafka. It's not even node. This library needs a lot of work still and it has many small gotchas. And at the same time for some reason no other alternative has emerged.

**Comment by vivekpathak** [comment]
> One way to handle this situation is to open a timeout with `setTimeout` before you send. The timeout would close the connection (and wait for callback) and then reconnect before calling send with the same parameters. This way you dont hang and come out even if kafka/zookeeper are down.
> 
> On the non error side, once the (original) send completes, the timeout should be cleared with `clearTimeout` because there is no need to resend.
> 
> It seems to work well when kafka/zk are up and recovers nicely from a restart.

Workaround is robust even on planetary scale iot data transfer being done through kafka 

Because its an underlying node library issue to do with one sided socket close, it should be Ok to use workaround (which can be considered to be the right way to do things since node socket close is one sided).
