### ISSUE TITLE
Rebalance consumerGroup "UnknownMemberId: Kafka Error Code: 25"

### ISSUE THREAD

**Issue by 0xslipk** [SOHU-Co/kafka-node#1355]
## Bug Report

consumer A and B will subscribe with the same groupId `kafka-test-group`
consumer A and B startup in the same time
consumer A registers itself as leader, and owns the topic with all partitions
consumer B registers itself as leader, and then begins to rebalance and owns all partitions
consumer A rebalance and obtains all partitions, but can not consume because the memberId is old and need a new one
consumer B rebalance again and owns the topic with all partitions, but it's already obtained by consumer A

This process repeat over and over again, as you can see in the example video.

### Environment

* Node version: 11
* Kafka-node version: 5.0.0
* Kafka version: 2.3.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 5

### Include Sample Code to reproduce behavior
https://github.com/jarcodallo/kafka-node/tree/fix-rebalance-with-kafka-v2.3/integrations/consumers

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Example: [rebalance-with-kafka-v2.3](https://drive.google.com/file/d/1i9Jve7axb1IE_PuEMnya5D8jPKJVGuOO/view?usp=sharing)

Logs from containers:
[consumer-1.log](https://github.com/SOHU-Co/kafka-node/files/3849696/consumer-1.log)
[consumer-2.log](https://github.com/SOHU-Co/kafka-node/files/3849705/consumer-2.log)

**Comment by 0xslipk** [comment]
@hyperlink can you check this issue?

**Comment by milos-josic** [comment]
I am experiencing this same issue as well. 

Two different consumers from same consumer group are consuming all partitions instead of them splitting between each other.

This " Heartbeat error: { UnknownMemberId: Kafka Error Code: 25" is present in logs from both consumers.

**Comment by StorkZ** [comment]
Hello, 
I have the same issue.
@jarcodallo did you manage to fix this somehow?

**Comment by 0xslipk** [comment]
@StorkZ unfortunately not, now I'm evaluate using another library like [kafka.js](https://github.com/tulios/kafkajs) or [rdkafka](https://github.com/Blizzard/node-rdkafka).

**Comment by StorkZ** [comment]
@jarcodallo I managed to fix it by changing configuration of kafka. 
I had been using single broker in docker container, because I wanted to be able to run integration tests. 
My config worked for basic cases, but caused this error. 
Now I'm using config described in this post: https://www.kaaproject.org/kafka-docker

**Comment by sandeepbbk** [comment]
Looks like this issue has something to do with the protocol clients use in JoinGroup request and Kafka Server version 2.3.0. The issue is fixed in Kafka Server 2.3.1.
PR: https://github.com/apache/kafka/pull/7072/files

Looking at kafka-node client code, looks like it uses version 0 of JoinGroup request which was broken in Kafka Server 2.3.0. We upgraded the server to 2.3.1 and checked and the issue seems to be resolved.

**Comment by 0xslipk** [comment]
@sandeepbbk you right. kafa-node works fine with kafka 2.3.1 and the issue with rebalance is fixed. I open a PR #1383 in order to add tests with kafka 2.3.1
