### ISSUE TITLE
Why the kafka client closed every 10 minutes?

### ISSUE THREAD

**Issue by yingzi20** [SOHU-Co/kafka-node#1377]
## Questions?

Why the kafka client closed every 10 minutes?

### Environment

* Node version: latest
* Kafka-node version: 5.0.0
* Kafka version:2.2.0

### For specific cases also provide
* Number of Brokers:3
* Number partitions for topic:50

### Include Sample Code to reproduce behavior

```js
// include code here
this.connect.once('close', (err) => {
      console.error('the client closed: ', err);
    });
    this.connect.once('error', (err) => {
      console.error('the client error: ', err);
    });
    this.connect.once('socket_error', (err) => {
      console.error('the client socket error: ', err);
    });
```

**Comment by 0chris** [comment]
I'm also having this issue. Actually there's a close event triggered and then a connect event out of nowhere.

**Comment by deepal** [comment]
Could be because your KafkaClient is idle for more than 10 minutes. By default, Kafka server's idle connection timeout is 10 minutes which is configured by `connections.max.idle.ms` in Kafka broker configuration. If the Kafka client is idle for 10 minutes, the Kafka broker disconnects the client.

If this is the issue, you can either increase the `connections.max.idle.ms` in the Kafka broker config or set KafkaClient's `reconnectOnIdle ` property to `true` which will allow KafkaClient to re-establish the connection when this happens.

See kafka broker config here: http://kafka.apache.org/090/documentation.html

**Comment by matan44** [comment]
@yingzi20 did you find a solution for this? Experiencing the same thing
