### ISSUE TITLE
LeaderNotAvailable error is coming

### ISSUE THREAD

**Issue by satty123** [SOHU-Co/kafka-node#227]
Hi,
I am trying to push data for a topic from node producer..

Its unable to push data in kafka
please suggest.

  function connectBroker(){
    client = new kafka.Client(IP:2181);
    producer= new kafka.HighLevelProducer(client);
    producerReady=false;
    producer.on('error',function(err){
      log.info(err)
      producer.close(function(){
        connectBroker();
      });
    });
    producer.on('ready',function(){
      producerReady=true;
    });
  }
  connectBroker();
    return{
      publishTopic:function(topic,data,cb){
        var keyedMessage=new kafka.KeyedMessage(data.key,data.value);
        var payload = [{ topic: topic, messages: [keyedMessage]}];
        if(!producerReady){
          producer.on('ready',function(){
            producerReady=true;
            producer.send(payload,function(err,data){
              cb(err,data);
            });
          });
        }
        else{
          producer.send(payload,function(err,data){
            cb(err,data);
          });
        }

      }
    }

})();
module.exports=Producer;

kafkaProducer.publishTopic("npsData",{"key":hotelReview.genericId,"value":JSON.stringify(obj)},function(err,data){})

on kafka
bin/kafka-topics.sh --topic  npsData  --describe --zookeeper 10.70.210.63:2181
Topic:npsData	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: npsData	Partition: 0	Leader: none	Replicas: 0	Isr: 

it will be great if some guide me to resolve it.

**Comment by zcei** [comment]
First, it'd be nice, if you take the time to format your code properly.

The issue is "automatically resolved" once you got this error.
If you try to push to a new topic it will be created, but at this point the kafka servers didn't had time to elect a leader for this topic.

My approach is to explicitly create topics (which catches `LeaderNotAvailable` errors), e.g. in build step or directly before the server is running.
