### ISSUE TITLE
kafka-node producer Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by asdfs1** [SOHU-Co/kafka-node#530]
I have a question with kafka-node , plesase help me out. Here is the link of my question
[http://stackoverflow.com/questions/40966337/kafka-node-producer-error-connect-etimedout](url)

**Comment by gogorush** [comment]
Guess you should not create a new producer for each request, move the client and producer out of your exports.Kafkatest = function(req,res) {} code block so that it won't create a new socket to the kafka server every time there is a new post request.
BTW: You should not simply post a stackoverflow link in github so that we could see the issue directly , cheers. @asdfs1
