### ISSUE TITLE
Help: Manually committing offset while using ConsumerGroup

### ISSUE THREAD

**Issue by vidhill** [SOHU-Co/kafka-node#576]
I have been trying to do the same thing, I have referenced a similar issue https://github.com/SOHU-Co/kafka-node/issues/502 but couldn't see a clear answer.

I have a consumerGroup,
I have configured it with autoCommit: false

To manually commit the offset I had to use consumer.client.sendOffsetCommitV2Request(...)
Is this correct? 

I couldn't get it to work using any other methods,
did I miss something?

**Comment by hyperlink** [comment]
My advice referenced in the previous thread still stands.

You should be able to manually commit by calling `autoCommit` or the alias of it `commit`.

```javascript
consumerGroup.commit(true, callback);
```

**Comment by sfrooster** [comment]
I'm a little confused here.

We only use ConsumerGroup's, and we are running with v0.10 brokers.

Previously, our ConsumerGroup's were using the Client object and were manually committing by calling Client.sendOffsetCommitV2Request.

We have switched to using the new KafkaClient (by setting the kafkaHost on the options) with our ConsumerGroup's, and we continue to manually commit by calling Client.sendOffsetCommitV2Request (because KafkaClient inherits from Client).

Above, you suggest calling autoCommit/commit (on HighLevelConsumer because ConsumerGroup inherits from HighLevelConsumer), but that still ends-up calling Client.sendOffsetCommitRequest and not Client.sendOffsetCommitV2Request.

We use V2 because there were issues with V0 which we did not have with V2 (I don't recall what they were, but they were critical).

Is there any reason for us to stop using V2?

**Comment by hyperlink** [comment]
This should continue to work since we override [sendOffsetCommitRequest](https://github.com/SOHU-Co/kafka-node/blob/master/lib/consumerGroup.js#L569) method to call the correct commit version in the client.

If possible you should avoid interacting with the client that lives inside the `ConsumerGroup` in case this changes in the future.

I plan on adding better support for manual commits in the future since it's frequently requested.

**Comment by sfrooster** [comment]
Ah, yes, I see.  I'll try switching to use ConsumerGroup.commit and see if that doesn't work for us.
