### ISSUE TITLE
Pause on topics in consumer group

### ISSUE THREAD

**Issue by divgwd** [SOHU-Co/kafka-node#611]
Hi,
I wanted to know if there is a way to pause on the complete topic rather than a partition in consumergroup.
We have our kafka consumergroup which reads from topics and inserts it into my backend database ,In the eventuality that my database goes down i would want my consumer groups read to be paused till the database comes up after that resume from the latest commited offset.Is there a way to do that in consumer group without specifying  partitions instead only topics ??

**Comment by hyperlink** [comment]
I don't know of any mechanism to do this in kafka since members of the group can only read from the partitions that were assigned by the leader.

Since each member in the group makes inserts into the database you could `close` the consumer group once you detect the database is disconnected and when it's reconnected again instantiate a new consumergroup one when the database comes back.
