### ISSUE TITLE
If this node.js client support produce AVRO message?

### ISSUE THREAD

**Issue by JohnnyZHH** [SOHU-Co/kafka-node#646]
If this node.js client support produce AVRO message?

**Comment by hyperlink** [comment]
We're doing this right now without any issues.

**Comment by JohnnyZHH** [comment]
Hi,

Thanks for your reply!

Could you please provide a example about how to encode avro message and send to kafka server?

**Comment by JohnnyZHH** [comment]
Hi,

If below usage is right?

var avro = require('avsc');
var schema = avro.parse({"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]});
var obj = {"f1":"value1"};
var data = schema.toBuffer(obj);

Then send "messages: Buffer.from(data.buffer)"

**Comment by hyperlink** [comment]
I haven't run the code but it looks reasonable to me. `kafka-node` doesn't care what data format you set as your message.

**Comment by philippschladitz** [comment]
The code provided by @JohnnyZHH is not working. The avro-schema is not detected because the message is either a buffer or string.

**Comment by longbkit** [comment]
Hi @hyperlink why did you close this article? The code sample is not working.

**Comment by longbkit** [comment]
Update:
It is correct that kafka-node can be used to send avro format message, as it can send a buffer and avro message is just a buffer.

In the example from JohnnyZHH above, just replace:
messages: schema.toBuffer(obj)

For more information, you can refer to this article https://blog.mimacom.com/apache-kafka-with-node-js/
Moreover, the reason that somebody as well as me was confusing was that the message serialized by avsc library cannot be decoded by avro consumer from confluent. It turns out because confluent platform use wire format with some more magic bytes in the begin of the buffer.
https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format

Good news is that there is a node package providing encoding message in wireformat that understood by Confluent Platform. https://www.npmjs.com/package/avro-schema-registry

Hope this helps.

**Comment by narcisoguillen** [comment]
Hey, I had to encode and decode messages using [avro](https://github.com/mtth/avsc).  I made this package to make things simple, so far I've being using it, hope it works for you too.  

https://www.npmjs.com/package/kafka-node-avro


```
const Settings = {
    "brokers" : "localhost:9092",
    "schema": {
      "registry" : "http://schemaregistry.example.com:8081"
    }
  };

KafkaAvro.init(Settings).then( kafka => {
  kafka.send({
    topic    : 'my.cool.topic',
    messages : { f1 : 'value1' }
  }).then( success => {
    // Message was sent encoded with Avro Schema
  }, error => {
    // Something wrong happen sending message
  });
} , error => {
  // something wrong happen initializing kafka
});
```

**Comment by hq-mobile** [comment]
> Update:
> It is correct that kafka-node can be used to send avro format message, as it can send a buffer and avro message is just a buffer.
> 
> In the example from JohnnyZHH above, just replace:
> messages: schema.toBuffer(obj)
> 
> For more information, you can refer to this article https://blog.mimacom.com/apache-kafka-with-node-js/
> Moreover, the reason that somebody as well as me was confusing was that the message serialized by avsc library cannot be decoded by avro consumer from confluent. It turns out because confluent platform use wire format with some more magic bytes in the begin of the buffer.
> https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format
> 
> Good news is that there is a node package providing encoding message in wireformat that understood by Confluent Platform. https://www.npmjs.com/package/avro-schema-registry
> 
> Hope this helps.

The key piece of information I was missing here is to set the consumer up with a 'buffer' encoding. When it was attempting to consume the message as a String I was receiving all sorts of errors from illegal union to index out of bounds. My Consumer now looks something like this...

```
kafkaConsumer = new Consumer(kafkaClient, [{ topic: kafkaTopic }], {
        encoding: 'buffer',
});

kafkaConsumer.on('message', (message) => {
        const value = Buffer.from(message.value, 'binary');
        const invoice = KafkaInvoice.fromBuffer(value);
        // Do something with Invoice
});
```
