### ISSUE TITLE
How do I set the value for offset customization?

### ISSUE THREAD

**Issue by kylezhang** [SOHU-Co/kafka-node#728]
## Scenes:
Kafka cluster, through the zookeeper maintenance, the consumption of the offset stored in the zookeeper, so the next time directly from the zookeeper offset, began to consume.

## Questions?
When using the ConsumerGroup, how to customize the offset to start consumption, for example: 'offset = 1234' which mean's from Offset 1234 starting consumption, instead of fromOffset is fixed the latest, earliest, none three.

**Comment by kylezhang** [comment]
I noticed it:
`Offsets, group members, and ownership details are not stored in Zookeeper`
But our project Architecture use zookeeper to save offset。

**Comment by hyperlink** [comment]
`ConsumerGroup` only stores offsets in Kafka please use `HighLevelConsumer` if you want to store them in zookeeper.

**Comment by kylezhang** [comment]
Thanks for your answer.
1) This HighLevelConsumer has been deprecated in the latest version of Kafka (0.10.1) and is likely to be removed in the future. Please use the ConsumerGroup instead.
2) If I use ConsumerGroup, at the beginning of consumption, I seem to be unable to   set the value of offset customize,too.

**Comment by hyperlink** [comment]
`HighlevelConsumer` is your only choice if you must use zookeeper.

You can start the HighlevelConsumer at a custom offset and then migrate over to the ConsumerGroup using it's auto migration feature-- this maybe a workaround for what you're trying to do.  Though it maybe dangerous since you could run into out of retention errors by provide a specific offset to consume from. So using the `earliest` option is safest.
