### ISSUE TITLE
KafkaClient::connectToBrokers iterates only once

### ISSUE THREAD

**Issue by wooyeong** [SOHU-Co/kafka-node#764]
I've been inventing another wheel of #558.

While getting brokers by using `kafkaClient.getBrokers()`, it always gave me one broker unlike its name suggests. I tried debugging, then I found `connectToBrokers()` may have a bug.

Please look below code.

https://github.com/SOHU-Co/kafka-node/blob/77c005a24039df6ba0ea36e4ef2aef3199e9ccd9/lib/kafkaClient.js#L148-L181

IMHO, this function is intended **to connect to all brokers**. However in `test` function,
https://github.com/SOHU-Co/kafka-node/blob/77c005a24039df6ba0ea36e4ef2aef3199e9ccd9/lib/kafkaClient.js#L168
by `!broker` condition, if we found any single valid broker, broker is not null, `test` fails, so it returns.

Therefore, we connect to the only first broker even we have more than one brokers.

Please let me know if I misunderstood the logic, or I'll post PR.
Thanks!

**Comment by hyperlink** [comment]
`getBrokers` should only returns currently connected brokers made by the client.

**Comment by wooyeong** [comment]
Okay, I read README says 'ready' event emitted after module is connected to **a broker**, not brokers.

What I want to is using 'ListGroups', and I've been implemented that protocol on the module and it works. According to the protocol, [ListGroups](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ListGroupsRequest) should be called over ALL brokers.

I tried the following,
```
`connect` -> `connectToBrokers` -> 'ready' event -> `getBrokers`
```
and what I expected was `connectToBrokers` would connect to all brokers and `getBrokers` would return all connected brokers but they don't by design, I understand that.

To use ListGroups protocol, there should be an API that let the client connect to all `initialHost` brokers.

What can I do in this situation? Can you advise me please?

**Comment by hyperlink** [comment]
We only need to successfully connect to a single broker in order to discover (using a metadata request) all the other brokers in the cluster. The client is designed to lazily connect to brokers depending on the need of the user. 

Here's how I would implement this:

1. Wait for `ready` event from `KafkaClient`
2. inspect `client.brokerMetadata` to see all the available brokers and their broker IDs
3. For each broker ID call your ListGroups using the BrokerWrapper result from `client.brokerForLeader(brokerId)` 

Hope that helps.

**Comment by wooyeong** [comment]
Thanks you. I'll try out later.
