### ISSUE TITLE
Kafka-node Producer does not recover from UnknownTopicOrPartition error

### ISSUE THREAD

**Issue by chaintng** [SOHU-Co/kafka-node#968]
I think it's very similar to this issue
https://github.com/SOHU-Co/kafka-node/issues/319

But only for producer case

When i changed producer to connect to new topic
I got an error `UnknownTopicOrPartition`
When it tried to produce a message to new topic.

I think we should fix the same to https://github.com/SOHU-Co/kafka-node/commit/ac70b9e79b1f48a1063ece8c8c6ef2def379f012
but for producer.

Do you have any workaround?

In the mean time, I will create a PR

**Comment by chaintng** [comment]
please ignore this

**Comment by david-benes** [comment]
Hi @chaintng, please reopen this. I encountered the exactly same issue you described here. However, I was able to reproduce it with a topic named 'test'. 

This is how I reproduced the issue:

1. prepared a cluster of 2 brokers
2. created a test topic with 1 partition and replication-factor 1
3. prepared a producer script from https://github.com/SOHU-Co/kafka-node/blob/master/example/producer.js
4. started producer
5. called kafka-reassign-partitions.sh to move the only partition to the next broker

I would expect the client to handle change in partitions. Instead, UnknownTopicOrPartition error is being thrown for all following produce requests (until the partition is moved back or producer restarted).

I already have a fix for this. The fix is similar to https://github.com/SOHU-Co/kafka-node/commit/62fc39bd9335d5aebcc4d21cbe0a50ca34c4b742.

**Comment by chaintng** [comment]
@david-benes I think it would better to create new issue. Because the original problem of my issue is already solved.
